# -*- coding: utf-8 -*-
"""cyberAttackClassificationModel_Refinado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIra8dJcTpuEjsTY3v9se3oWqA2rEEtD

# Cyber Attack Classification Model - Random Forest

Binary classification of HTTP requests as Valid (0) and Anomalous (1) using Random Forest

OWASP CRS reference

https://owasp-org.translate.goog/www-project-modsecurity-core-rule-set/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc

https://github.com/coreruleset/coreruleset/tree/main/rules
"""

#Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
df = pd.read_csv("/content/ecml_pkdd_2007_web_attacks.csv")
df.head()

df.shape

df.isnull().sum()

df.nunique()

df.info()

#Clean the data

#Delete columns Host, Content-Type
df = df.drop(columns=["Host", "Content-Type"])

# Normalize objetive variable
df["Class"] = df["Class"].str.lower()
df = df[df["Class"].isin(["valid", "anomalous"])].copy()

y = df["Class"].map({"valid": 0, "anomalous": 1}).astype(int)

# Convert Content-Length to numeric
df["Content-Length"] = pd.to_numeric(df["Content-Length"], errors="coerce").fillna(0)

df.shape

#Determine the independent variables and dependent variable
#  x = features of the HTTP request
#  y = Valid = 0, Anomalous = 1

# Create numeric features from the text of the HTTP requests.
# Avoiding creating too many columns with get_dummies on long text variables.

x = pd.DataFrame(index=df.index)

# Original numeric variable
x["Content-Length"] = df["Content-Length"]

# Columns where web attacks usually appear
attack_text_cols = ["URI", "GET-Query", "POST-Data", "Cookie", "User-Agent"]

# Length of each text field, because attack requests are usually abnormally long, so the length is a useful signal.
for col in attack_text_cols:
    new_col = "len_" + col.replace("-", "_")
    x[new_col] = df[col].astype(str).str.len()

# Text to look for suspicious patterns
request_text = df[attack_text_cols].astype(str).agg(" ".join, axis=1).str.lower()

# Basic attack indicators used in OWASP CRS
x["has_sql_kw"] = request_text.str.contains(
    r"\b(?:union|select|drop|insert|delete|update|where|from)\b", regex=True
).astype(int)

x["has_xss_kw"] = request_text.str.contains(
    r"script|javascript|onload|onerror|alert|iframe", regex=True
).astype(int)

x["has_traversal"] = request_text.str.contains(
    r"\.\./|\.\.\\|/etc/passwd|cmd\.exe|winnt|boot\.ini", regex=True
).astype(int)

x["has_encoded"] = request_text.str.contains(
    r"%2f|%3c|%3e|%27|%22|%28|%29", regex=True
).astype(int)

x["has_admin"] = request_text.str.contains(
    r"admin|login|password|passwd|root", regex=True
).astype(int)

# Counts of symbols frequently seen in web attacks
x["cnt_equal"] = request_text.str.count(r"=")
x["cnt_ampersand"] = request_text.str.count(r"&")
x["cnt_percent"] = request_text.str.count(r"%")
x["cnt_slash"] = request_text.str.count(r"/")
x["cnt_dot"] = request_text.str.count(r"\.")
x["cnt_quote"] = request_text.str.count(r"'") + request_text.str.count(r'"')
x["cnt_semicolon"] = request_text.str.count(r";")
x["cnt_comment"] = request_text.str.count(r"--")

# Extended OWASP CRS attack-category indicators

# CRS 932 — Remote Code Execution
x["has_rce_kw"] = request_text.str.contains(
    r"\b(?:eval|exec|system|passthru|shell_exec|popen|proc_open|assert|create_function)\b|"
    r"\$\(|`[^`]+`|"
    r";\s*(?:cat|ls|whoami|id|uname|ps|wget|curl|nc|ncat|telnet|chmod|rm)\b|"
    r"\|\s*(?:cat|ls|whoami|id|uname|ps|wget|curl|nc|ncat)\b|"
    r"&&\s*(?:cat|ls|whoami|id|uname)|"
    r"/bin/(?:sh|bash|dash|csh|tcsh|zsh)|/usr/bin/|/usr/local/bin/",
    regex=True,
).astype(int)

# CRS 930 — Local File Inclusion
x["has_lfi_kw"] = request_text.str.contains(
    r"/etc/(?:passwd|shadow|hosts|group|sudoers|nginx|apache)|"
    r"/proc/self/|/proc/version|/proc/cpuinfo|"
    r"php://(?:filter|input|memory|fd)|"
    r"file://|expect://|data:text",
    regex=True,
).astype(int)

# CRS 931 — Remote File Inclusion
x["has_rfi_kw"] = request_text.str.contains(
    r"=https?://|=ftp://|file=https?://|include=https?://|page=https?://",
    regex=True,
).astype(int)

# CRS 933 — PHP attacks
x["has_php_attack"] = request_text.str.contains(
    r"<\?php|<\?=|"
    r"\$_(?:get|post|request|cookie|server|env|files|session|globals)|"
    r"base64_decode|gzinflate|str_rot13|"
    r"preg_replace.*?/e|php://",
    regex=True,
).astype(int)

# XXE — XML External Entity
x["has_xxe"] = request_text.str.contains(
    r"<!entity|<!doctype[^>]*\[|system\s+[\"']file:|system\s+[\"']http:",
    regex=True,
).astype(int)

# CRS 944 — Log4Shell / JNDI injection
x["has_log4j"] = request_text.str.contains(
    r"\$\{jndi:|\$\{lower:|\$\{upper:|"
    r"ldap://|ldaps://|rmi://|nis://|nds://|iiop://|corba://|dns://",
    regex=True,
).astype(int)

# NoSQL injection
x["has_nosql"] = request_text.str.contains(
    r"\$ne\b|\$gt\b|\$lt\b|\$gte\b|\$lte\b|\$in\b|\$nin\b|"
    r"\$or\b|\$and\b|\$where\b|\$regex\b|\$exists\b|"
    r"db\.[a-z_]+\.(?:drop|find|update|remove|delete|insert)",
    regex=True,
).astype(int)

# PHP serialized objects (deserialization attacks)
x["has_serialization"] = request_text.str.contains(
    r"o:\d+:\"|a:\d+:\{|s:\d+:\"|i:\d+;|b:[01];",
    regex=True,
).astype(int)

# CRS 941 — XSS expanded
x["has_xss_advanced"] = request_text.str.contains(
    r"on(?:load|error|mouseover|focus|click|keyup|submit|change|blur)\s*=|"
    r"javascript:|data:text/html|vbscript:|"
    r"<svg|<iframe|<embed|<object|"
    r"alert\(|prompt\(|confirm\(|"
    r"document\.cookie|document\.write|window\.location",
    regex=True,
).astype(int)

# CRS 942 — SQLi expanded
x["has_sql_advanced"] = request_text.str.contains(
    r"union\s+(?:all\s+)?select|"
    r"information_schema|"
    r"\bsleep\s*\(|benchmark\s*\(|waitfor\s+delay|"
    r"\bchar\s*\(\s*\d+|\bascii\s*\(|substr(?:ing)?\s*\(|"
    r"or\s+\d+\s*=\s*\d+|or\s+[\"']\w+[\"']\s*=\s*[\"']\w+[\"']|"
    r"--[ \t]|/\*.*?\*/|#\s",
    regex=True,
).astype(int)

# Sensitive file probing
x["has_sensitive_file"] = request_text.str.contains(
    r"\.git/|\.env\b|\.htaccess|\.htpasswd|"
    r"\.bak\b|\.backup\b|\.old\b|\.orig\b|\.swp\b|\.swo\b|"
    r"web\.config|wp-config\.php|configuration\.php|"
    r"\.ds_store|\.ssh/|id_rsa|\.pem\b|\.key\b|"
    r"/.well-known/",
    regex=True,
).astype(int)

# Admin/management paths probing
x["has_admin_path"] = request_text.str.contains(
    r"/admin|/administrator|/wp-admin|/wp-login|"
    r"/phpmyadmin|/pma\b|/myadmin|/dbadmin|/sqladmin|"
    r"/manager|/console|/dashboard|/cpanel|"
    r"/_admin|/sysadmin|/adminer|/setup\.php|/install\.php",
    regex=True,
).astype(int)

# Suspicious script extensions
x["has_shell_extension"] = request_text.str.contains(
    r"\.(?:sh|pl|py|rb|jsp|asp|aspx|cgi|cmd|bat|war|jar)(?:[?\b/]|$)",
    regex=True,
).astype(int)

# Double URL encoding (evasion)
x["has_double_encoded"] = request_text.str.contains(
    r"%25(?:3c|3e|22|27|28|29|2f|5c|3d|26|2e)",
    regex=True,
).astype(int)

# Null byte injection
x["has_null_byte"] = request_text.str.contains(
    r"%00|\\x00|\\u0000",
    regex=True,
).astype(int)

# User-Agent fingerprinting (CRS 913 — scanner detection)
ua = df["User-Agent"].astype(str).str.lower()

# Scanners y herramientas ofensivas conocidas
x["ua_scanner"] = ua.str.contains(
    r"nikto|sqlmap|nmap|w3af|burp|acunetix|nessus|openvas|"
    r"masscan|fimap|wfuzz|skipfish|nuclei|httpx|"
    r"dirb|gobuster|wpscan|hydra|metasploit",
    regex=True,
).astype(int)

# Librerias HTTP - potencialmente bots / clientes automatizados
x["ua_lib"] = ua.str.contains(
    r"curl/|wget/|python-requests|python-urllib|libcurl|"
    r"java/|go-http-client|okhttp|apache-httpclient|node-fetch",
    regex=True,
).astype(int)

# Navegadores reales (señal de trafico humano legit)
x["ua_browser"] = ua.str.contains(
    r"mozilla/|applewebkit|chrome/|firefox/|safari/|edge/|opera/",
    regex=True,
).astype(int)

x["ua_len"] = ua.str.len()
x["ua_word_count"] = ua.str.split().str.len().fillna(0)

#

# Categorical variables with low cardinality
cat_cols = ["Method", "Host-Header"]

x_cat = pd.get_dummies(df[cat_cols], drop_first=True, dtype=int)

# Join numeric and categorical variables
x = pd.concat([x, x_cat], axis=1)

# Ensure there are no null values
x = x.fillna(0)

x.head()

plt.figure(figsize=(10, 8))
sns.heatmap(
    x.select_dtypes(include="number").corr(),
    annot=True,
    fmt=".2f",
    annot_kws={"size": 8}
)
plt.title("Features correlation")
plt.show()

#Split dataset to train and test parts
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=10
)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

#Create the model
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=100, random_state=10)
RF.fit(x_train, y_train)

#Predict the output of the test data
y_predict = RF.predict(x_test)

#Evaluate the model
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_predict))

print("\nClassification Report:\n")
print(classification_report(y_test, y_predict, target_names=["Valid", "Anomalous"]))

# Actual vs Predicted: distribución real y resultados del modelo
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Gráfica 1: distribución del y actual (y_test)
axes[0].bar(["Valid", "Anomalous"],
            [sum(y_test == 0), sum(y_test == 1)],
            color=["#2ecc71", "#e74c3c"])
axes[0].set_title("Actual y (y_test)")
axes[0].set_ylabel("Count")
for i, v in enumerate([sum(y_test == 0), sum(y_test == 1)]):
    axes[0].text(i, v + 10, str(v), ha="center", fontweight="bold")

# Gráfica 2: distribución del y predicho (y_predict)
axes[1].bar(["Valid", "Anomalous"],
            [sum(y_predict == 0), sum(y_predict == 1)],
            color=["#3498db", "#e74c3c"])
axes[1].set_title("Predicted y (y_predict)")
axes[1].set_ylabel("Count")
for i, v in enumerate([sum(y_predict == 0), sum(y_predict == 1)]):
    axes[1].text(i, v + 10, str(v), ha="center", fontweight="bold")

plt.suptitle("Actual vs Predicted Distribution", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

importances = RF.feature_importances_
indices = np.argsort(importances)[::-1][:10]

plt.figure(figsize=(10, 5))
plt.bar(range(10), importances[indices], color="#3498db")
plt.xticks(range(10), [x.columns[i] for i in indices], rotation=45, ha="right")
plt.ylabel("Importance")
plt.title("Top 10 Feature Importances")
plt.tight_layout()
plt.show()

from sklearn.model_selection import learning_curve


train_sizes, train_scores, test_scores = learning_curve(
    RF, x, y,
    train_sizes=np.linspace(0.1, 1.0, 6),
    cv=3,
    scoring="accuracy",
    random_state=10,
    n_jobs=-1
)

train_mean = train_scores.mean(axis=1)
test_mean  = test_scores.mean(axis=1)

fig, ax = plt.subplots(figsize=(10, 5))
ax.set_facecolor("white")
ax.grid(True, linestyle="--", linewidth=0.6, color="gray", alpha=0.6)

ax.scatter(train_sizes, train_mean, color="#1f6eb5", s=40, zorder=3, label="Train")
ax.scatter(train_sizes, test_mean,  color="#e07b00", s=40, zorder=3, label="Test")
ax.axhline(y=test_mean[-1], color="red", linewidth=1.5,
           label=f"Test final: {test_mean[-1]:.3f}")

ax.set_xlabel("Tamaño del conjunto de entrenamiento", fontsize=11)
ax.set_ylabel("Accuracy", fontsize=11)
ax.set_title("Learning Curve — Train vs Test", fontsize=13)
ax.set_ylim(0.5, 1.05)
ax.legend(frameon=True, fontsize=10)
for spine in ["top", "right"]:
    ax.spines[spine].set_visible(False)

plt.tight_layout()
plt.show()
