// Mock data para el boceto del dashboard SOC.
// Reemplazar con llamadas reales al backend (issues #8 y #10) cuando esté.
//
// Los eventos están inspirados en patrones reales del dataset ECML/PKDD 2007
// que usa nuestro modelo (SQLi, XSS, path traversal, encoded payloads, admin probing).

export const kpis = [
  {
    id: 'total',
    label: 'Total requests',
    value: 12394,
    delta: '+12.4%',
    deltaDirection: 'up',
    period: 'vs ayer',
    sparkline: [820, 940, 1100, 1050, 980, 1240, 1310, 1450, 1380, 1290, 1410, 1530],
    accent: 'cyan',
  },
  {
    id: 'blocked',
    label: 'Bloqueados',
    value: 1832,
    delta: '+8.1%',
    deltaDirection: 'up',
    period: 'vs ayer',
    sparkline: [110, 132, 158, 145, 142, 188, 201, 215, 198, 184, 207, 234],
    accent: 'rose',
  },
  {
    id: 'rate',
    label: 'Block rate',
    value: '14.7%',
    delta: '-0.6 pp',
    deltaDirection: 'down',
    period: 'vs ayer',
    sparkline: [13.4, 14.0, 14.4, 13.8, 14.5, 15.2, 15.4, 14.8, 14.4, 14.2, 14.7, 15.3],
    accent: 'amber',
  },
  {
    id: 'top-attack',
    label: 'Top attack type',
    value: 'SQLi',
    delta: '41% de bloqueos',
    deltaDirection: 'flat',
    period: '24h',
    sparkline: null,
    accent: 'violet',
  },
  {
    id: 'latency',
    label: 'Latencia WAF',
    value: '23 ms',
    delta: 'p99: 89 ms',
    deltaDirection: 'flat',
    period: 'media móvil',
    sparkline: [20, 22, 24, 21, 25, 28, 31, 27, 24, 22, 23, 25],
    accent: 'blue',
  },
  {
    id: 'attackers',
    label: 'Attackers únicos',
    value: 47,
    delta: '+5 nuevos',
    deltaDirection: 'up',
    period: '24h',
    sparkline: [38, 39, 40, 41, 41, 42, 43, 44, 45, 45, 46, 47],
    accent: 'rose',
  },
]

// Timeline de tráfico — 24 horas, granularidad por hora.
// Valid vs Anomalous stacked.
export const timeline = {
  buckets: Array.from({ length: 24 }, (_, h) => {
    const hour = (new Date().getHours() - 23 + h + 24) % 24
    const baseValid = 380 + Math.round(160 * Math.sin((h / 24) * Math.PI * 2 - 1))
    const baseAnom = 38 + Math.round(28 * Math.cos((h / 12) * Math.PI - 0.5))
    return {
      label: `${String(hour).padStart(2, '0')}:00`,
      valid: Math.max(120, baseValid + (h % 5) * 11),
      anomalous: Math.max(8, baseAnom + (h % 3) * 7),
    }
  }),
}

export const attackTypes = [
  { id: 'sqli', label: 'SQL Injection', value: 41, color: '#f43f5e' },
  { id: 'xss', label: 'Cross-Site Scripting', value: 23, color: '#fb7185' },
  { id: 'traversal', label: 'Path Traversal', value: 14, color: '#fbbf24' },
  { id: 'encoded', label: 'Payload Encoded', value: 11, color: '#a78bfa' },
  { id: 'admin', label: 'Admin Probing', value: 8, color: '#60a5fa' },
  { id: 'other', label: 'Otros', value: 3, color: '#8b94ad' },
]

export const topIPs = [
  { ip: '203.0.113.8', country: 'CL', total: 247, anomalousPct: 89, firstSeen: '06:12', lastSeen: '13:41', status: 'blocked' },
  { ip: '45.155.205.211', country: 'RU', total: 198, anomalousPct: 95, firstSeen: '08:33', lastSeen: '13:42', status: 'blocked' },
  { ip: '192.168.1.47', country: '—', total: 156, anomalousPct: 67, firstSeen: '07:01', lastSeen: '13:42', status: 'watch' },
  { ip: '198.51.100.15', country: 'NL', total: 89, anomalousPct: 78, firstSeen: '09:48', lastSeen: '13:36', status: 'blocked' },
  { ip: '172.16.10.5', country: '—', total: 64, anomalousPct: 41, firstSeen: '10:22', lastSeen: '13:30', status: 'watch' },
  { ip: '91.234.99.124', country: 'UA', total: 51, anomalousPct: 84, firstSeen: '11:05', lastSeen: '13:18', status: 'blocked' },
]

export const topEndpoints = [
  { uri: '/api/login', attacks: 312, total: 1840 },
  { uri: '/search', attacks: 187, total: 980 },
  { uri: '/admin/config.php', attacks: 142, total: 198 },
  { uri: '/wp-admin/setup-config.php', attacks: 98, total: 110 },
  { uri: '/api/users/:id', attacks: 76, total: 642 },
  { uri: '/api/comments', attacks: 54, total: 712 },
  { uri: '/index.php', attacks: 41, total: 220 },
]

export const modelHealth = {
  predictionsPerSecond: 142,
  rollingAccuracy: 0.918,
  drift: 0.07, // 0-1, mientras menos mejor
  confidenceHistogram: [
    { bin: '0.0-0.1', count: 4820 },
    { bin: '0.1-0.2', count: 3210 },
    { bin: '0.2-0.3', count: 1140 },
    { bin: '0.3-0.4', count: 480 },
    { bin: '0.4-0.5', count: 320 },
    { bin: '0.5-0.6', count: 290 },
    { bin: '0.6-0.7', count: 410 },
    { bin: '0.7-0.8', count: 680 },
    { bin: '0.8-0.9', count: 1120 },
    { bin: '0.9-1.0', count: 1690 },
  ],
  status: 'healthy',
}

// Eventos recientes — patrones tomados del dataset ECML/PKDD 2007.
export const recentEvents = [
  {
    id: 'evt-9281',
    ts: '13:42:11',
    ip: '192.168.1.47',
    method: 'POST',
    uri: '/api/login',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.94,
    attackType: 'sqli',
    rule: 'CRS-942100',
    body: '{"username":"admin","password":"\\u0027 OR 1=1 --"}',
    headers: {
      'Host': 'webshield.lab.tec.local',
      'User-Agent': 'curl/8.4.0',
      'Content-Type': 'application/json',
      'Content-Length': '52',
    },
    features: [
      { name: 'has_sql_kw', value: 1, contribution: 0.41 },
      { name: 'cnt_quote', value: 4, contribution: 0.18 },
      { name: 'cnt_comment', value: 1, contribution: 0.14 },
      { name: 'len_POST_Data', value: 52, contribution: 0.09 },
      { name: 'has_admin', value: 1, contribution: 0.07 },
    ],
  },
  {
    id: 'evt-9280',
    ts: '13:42:09',
    ip: '10.0.5.21',
    method: 'GET',
    uri: '/index.html',
    verdict: 'valid',
    action: 'allowed',
    score: 0.02,
    attackType: null,
    rule: null,
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0' },
    features: [],
  },
  {
    id: 'evt-9279',
    ts: '13:42:07',
    ip: '203.0.113.8',
    method: 'GET',
    uri: '/search?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.89,
    attackType: 'xss',
    rule: 'CRS-941100',
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'sqlmap/1.7.11', 'Referer': '/' },
    features: [
      { name: 'has_xss_kw', value: 1, contribution: 0.38 },
      { name: 'has_encoded', value: 1, contribution: 0.22 },
      { name: 'cnt_percent', value: 8, contribution: 0.13 },
      { name: 'len_GET_Query', value: 44, contribution: 0.09 },
    ],
  },
  {
    id: 'evt-9278',
    ts: '13:42:03',
    ip: '10.0.5.21',
    method: 'GET',
    uri: '/api/products?category=electronics',
    verdict: 'valid',
    action: 'allowed',
    score: 0.04,
    attackType: null,
    rule: null,
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0' },
    features: [],
  },
  {
    id: 'evt-9277',
    ts: '13:42:01',
    ip: '198.51.100.15',
    method: 'GET',
    uri: '/../../../../etc/passwd',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.97,
    attackType: 'traversal',
    rule: 'CRS-930100',
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'python-requests/2.31.0' },
    features: [
      { name: 'has_traversal', value: 1, contribution: 0.52 },
      { name: 'cnt_dot', value: 8, contribution: 0.24 },
      { name: 'cnt_slash', value: 5, contribution: 0.12 },
    ],
  },
  {
    id: 'evt-9276',
    ts: '13:41:55',
    ip: '192.168.1.47',
    method: 'POST',
    uri: '/api/comments',
    verdict: 'valid',
    action: 'allowed',
    score: 0.11,
    attackType: null,
    rule: null,
    body: '{"text":"nice article!","postId":42}',
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0', 'Content-Type': 'application/json' },
    features: [],
  },
  {
    id: 'evt-9275',
    ts: '13:41:48',
    ip: '203.0.113.8',
    method: 'GET',
    uri: '/admin/config.php',
    verdict: 'anomalous',
    action: 'flagged',
    score: 0.62,
    attackType: 'admin',
    rule: 'CRS-932100',
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0' },
    features: [
      { name: 'has_admin', value: 1, contribution: 0.31 },
      { name: 'cnt_dot', value: 2, contribution: 0.08 },
    ],
  },
  {
    id: 'evt-9274',
    ts: '13:41:42',
    ip: '10.0.5.21',
    method: 'POST',
    uri: '/api/checkout',
    verdict: 'valid',
    action: 'allowed',
    score: 0.08,
    attackType: null,
    rule: null,
    body: '{"cart":[{"id":1,"qty":2}]}',
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0', 'Content-Type': 'application/json' },
    features: [],
  },
  {
    id: 'evt-9273',
    ts: '13:41:33',
    ip: '45.155.205.211',
    method: 'GET',
    uri: '/wp-admin/setup-config.php?step=1',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.81,
    attackType: 'admin',
    rule: 'CRS-913100',
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0 (compatible; Nmap NSE)' },
    features: [
      { name: 'has_admin', value: 1, contribution: 0.34 },
      { name: 'len_URI', value: 32, contribution: 0.11 },
    ],
  },
  {
    id: 'evt-9272',
    ts: '13:41:21',
    ip: '192.168.1.47',
    method: 'GET',
    uri: '/api/user/1%20OR%201%3D1',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.91,
    attackType: 'sqli',
    rule: 'CRS-942110',
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'curl/8.4.0' },
    features: [
      { name: 'has_sql_kw', value: 1, contribution: 0.39 },
      { name: 'has_encoded', value: 1, contribution: 0.21 },
      { name: 'cnt_percent', value: 4, contribution: 0.11 },
    ],
  },
  {
    id: 'evt-9271',
    ts: '13:40:58',
    ip: '91.234.99.124',
    method: 'POST',
    uri: '/api/upload',
    verdict: 'anomalous',
    action: 'blocked',
    score: 0.86,
    attackType: 'other',
    rule: 'CRS-933100',
    body: '<?php system($_GET[\'c\']); ?>',
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'curl/8.4.0', 'Content-Type': 'application/octet-stream' },
    features: [
      { name: 'has_traversal', value: 0, contribution: 0.02 },
      { name: 'cnt_quote', value: 2, contribution: 0.08 },
      { name: 'len_POST_Data', value: 30, contribution: 0.05 },
    ],
  },
  {
    id: 'evt-9270',
    ts: '13:40:42',
    ip: '10.0.5.21',
    method: 'GET',
    uri: '/dashboard',
    verdict: 'valid',
    action: 'allowed',
    score: 0.03,
    attackType: null,
    rule: null,
    body: null,
    headers: { 'Host': 'webshield.lab.tec.local', 'User-Agent': 'Mozilla/5.0' },
    features: [],
  },
]

export const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: 'grid', active: true },
  { id: 'live', label: 'Live events', icon: 'pulse', badge: 'LIVE' },
  { id: 'alerts', label: 'Alerts', icon: 'bell', badge: 12 },
  { id: 'triage', label: 'Triage queue', icon: 'inbox', badge: 4 },
  { id: 'investigations', label: 'Investigations', icon: 'search' },
  { id: 'rules', label: 'Rules & model', icon: 'shield' },
  { id: 'users', label: 'Users', icon: 'users', adminOnly: true },
  { id: 'audit', label: 'Audit log', icon: 'history', adminOnly: true },
  { id: 'settings', label: 'Settings', icon: 'cog' },
]

export const currentUser = {
  name: 'Nat Rogue',
  email: 'natrogue28@gmail.com',
  role: 'analyst',
  initials: 'NR',
}
